### ISSUE TITLE
Suchauftrag eingeben (UC 1)

### ISSUE THREAD

**Issue by simbra92** [sweIhm/sweiproject-tg1a-2#1]
User Story: 
Als Student/in will ich für mich angeben, dass ich einen Praktikumsplatz im Ausland suche.

Akzeptanzkriterien: 
- Aktivitätseingabe auswählen
- Text eingeben

**Comment by maxiking203** [comment]
Im Backend muss dafür im Controller eine Methode implementiert werden, die einen HTTP POST entgegen nimmt und die angebenden Parametern in einen Post übernimmt. Dieser Post wird dann der Database hinzugefügt.
Diese Methode steht bereits aus dem 1.Sprint unter "/board" zu Verfügung, da die Post dort über das Postman-tool zugesendet werden konnten.

**Comment by brumma-man** [comment]
ready for review

**Comment by maxiking203** [comment]
Please check if the inserted values are not empty. At the moment it is possible to send a post that has no text.

**Comment by brumma-man** [comment]
adminview and regular board now check for empty text fields and valid e-mail addresses (only hm.edu domain so far). as long as a single tag is not empty, the tagList counts as valid.
We might want to cull empty tags in the future, though.

claimed fixed.

**Comment by maxiking203** [comment]
Seems good to me! Of course we can make it possible to post an activtiy without tags.

Another thing that I noticed was, that the textfield are not emtpy after I added my post. Is this just a thing on my browser or is this not implemnted at the moment?

**Comment by brumma-man** [comment]
nice catch.
changed javascript behaviour: after posting, site now automatically reloads, displaying the new posts in the list as well as clearing the text fields. 😎

**Comment by maxiking203** [comment]
Perfekt! Review made, can be closed!
