### ISSUE TITLE
Admin-Sicht öffnen (UC9)

### ISSUE THREAD

**Issue by wildeKaiserin** [sweIhm/sweiproject-tg1a-2#10]
User Story:
Als Administrator/in des Projekts will ich die Admin-Sicht öffnen, um alle Informationen der Posts zu sehen.

Akzeptanzkriterien:

- Admin-Sicht wird geöffnet

- alle Informationen eines Posts und des Erstellers werden angezeigt

**Comment by maxiking203** [comment]
Added an AdminController which opens the Admin view with the URL "tg1a-2.herokuapp/adminview".

**Comment by brumma-man** [comment]
ready for review

**Comment by maxiking203** [comment]
I thought that the admin-view shoud also provied the email-adresse of the author, shoud't it? 
(see Akzeptanzkriterien: alle Informationen eines Posts und des Erstellers werden angezeigt)

**Comment by brumma-man** [comment]
you are correct, visible data rows in adminview (and the regular board) have been adjusted accordingly.

claimed fixed.

**Comment by maxiking203** [comment]
Issue can be closed, all "Akzeptanzkriterien" fullfiled. Maybe one more Teammember should check.
