### ISSUE TITLE
Post löschen in der Admin-View (UC10)

### ISSUE THREAD

**Issue by wildeKaiserin** [sweIhm/sweiproject-tg1a-2#11]
User Story:
In der Admin-View will ich unangemessene Posts löschen.

Akzeptanzkriterien:

- Löschen Button entfernt den Post, sodass er nicht mehr angezeigt wird.

**Comment by maxiking203** [comment]
Method is now implemented in the Controller so the Frontend can send a delete Request. A Method to edit a post is also provieded.

**Comment by brumma-man** [comment]
ready for review. 🙏🏻

**Comment by maxiking203** [comment]
Nice! Review made, can be closed!
