### ISSUE TITLE
Versenden von Verifizierungscode per Mail an den Autor (UC11)

### ISSUE THREAD

**Issue by maxiking203** [sweIhm/sweiproject-tg1a-2#12]
Der Benutzer muss, bevor seinen Post veröffentlichen kann, einen Verifizierungscode anfordern. Dieser wir ihm an seine angeben E-Mailadresse gesendet. Dieser Code wird dann in Eingabemaske angeben und berechtigt dann zur Veröffentlichung.

Akzeptanzkriterien:
-Email wird automatisch versendet und Code berechtigt zum Veröffentlichen

**Comment by maxiking203** [comment]
This feauter is almost done. 
I'm testing selutions for not using the passowrd for the Email Sender in the Sourecode. The rest of the Code is done but commented in the Code so that the project is still able to run.

The first part is the verification Code. In Backend there is an Rest endpoint which send an code via Mail. This endpoint can be reached by sending an PUT request to /getCode/ + the email adress.

A new post then can be send in the old style with one change. The entered verification code has to be in URL for the request. So it will be a POST request to /board/{code} and the Post itself as json.

When the frontend change the request, added the new one for verification Code and the email Sender is commited, the new version can be activited by deleting the comments arround the new endpoints.

**Comment by maxiking203** [comment]
Added Environment Variables on heroku so the password do not need to stand in the sourcecode. I tested it once.

For Unit tests I already added the envirmoment Variables to Travis.
**Unit Test will come later this week. But keep in mind:**
When the Unit test are commited erveryone has to create new envirmoment Variables local on his PC named like the two on heroku. If you don't want to add new Variables you can simply comment the test to run or build the project local but never commit this test.

**Comment by brumma-man** [comment]
a PUT request to /getCode/sthum@hm.edu
fails with a 404:
{
    "timestamp": 1515505694489,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/getCode/sthum@hm.edu"
}

am I requesting the wrong URL?

**Comment by maxiking203** [comment]
yes, it's wrong, but my mistake...sorry. Should be a PUT request to **/board/getCode/**sthum@hm.edu

**Comment by brumma-man** [comment]
/board/getCode/(mail)
does not report a 404, but after 30 minutes, no e-mail has arrived (junk folder has been checked).

maybe you could try it yourselves, to see if it's just me?

(new post > enter hm e-mail address > request confirmation code)

**Comment by brumma-man** [comment]
haha, disregard.
arrived just this minute!

**Comment by brumma-man** [comment]
Posting now works with the correct code, and not with an incorrect code (no error message for the user so far)

fallback posting without any code at all (to /board) still works.
feel free to remove that from the backend at your leisure.

**Comment by maxiking203** [comment]
From my side it would be ready to review.

I will delete the endpoint which makes it able to post without the verification Code later.

**Comment by maxiking203** [comment]
review was made yesterday. Done
