### ISSUE TITLE
UC2 Extended: Mobile Ansicht

### ISSUE THREAD

**Issue by wildeKaiserin** [sweIhm/sweiproject-tg1a-2#13]
Das Layout der Website auf mobilen Geräten entspricht nicht den Erwartungen.
Das Problem lösen wir am Besten mit einer zweiten css-Datei, die für mobile optimiert ist.

Akzeptanzkriterien:
-Website ist auf mobilen Endgeräten benutzerfreundlich

**Comment by brumma-man** [comment]
Gute Idee!
Ich binde das zweite CSS dann für mobile User Agents direkt in das HTML von Index und AdminView ein.

**Comment by brumma-man** [comment]
mobile.css eingebunden, vorerst nur in die normale index, nicht den admin. 
Go hog wild.

**Comment by maxiking203** [comment]
mobile View is provieded. It's definitely easier to use the webapp.

I closes issue now, of course the view could be more optimized but there is no need for.
