### ISSUE TITLE
Erweiterung UC1: Post bekommt einen Titel und eine Kategorie

### ISSUE THREAD

**Issue by maxiking203** [sweIhm/sweiproject-tg1a-2#14]
Der Post aus den bereits vergangen Sprints wird erweitert um einen entsprechenden Titel und um einen einzige Kategorie, die im Frontend zur Auswahl stehen.

Akzeptanzkriterien:
-Anzeige von Titel und Kategorie im Frontend
-Junit Tests im Backend zum Post

**Comment by maxiking203** [comment]
Post entity is now expented in the backend (dev branch). After changes in the frontend dev and master can be merged so the meter can run on heroku with the new Post.
json for the new Post looks something like that: 
"{"emailAddr": "test@hm.edu","title": "TestTitle","postText": "Dies ist ein weiterer Test über das Postman-tool","tagList": ["#Test","#Test2","#Test3"],"category": "Test"}"

**Comment by brumma-man** [comment]
front end has linked up the fields for displaying and posting the new data model fields, but backend seems to deliver only the original fields so far.
you can check that out in your browser, we're printing the whole JSON to the console.

e.g. {listIndex: 100, emailAddr: "abc@hm.edu", postText: "der beste tag", tagList: ["croissants", " milchkaffee"], tagListAsString: "[croissants, milchkaffee]", …}

no "title", no "category".

**Comment by maxiking203** [comment]
title and category are only implemented in dev branch not in master branch. In the master branch the Post is currently running without title and category. After merching these two it should work.

**Comment by brumma-man** [comment]
oh. reading comprehension is not one of my strong points XD

ready for merge from the front end side then 👌🏻

**Comment by maxiking203** [comment]
Merge completed. Database reset. Running now 🥇

**Comment by brumma-man** [comment]
can confirm: viewing and posting with the extended post entity works without obvious problems.

**Comment by maxiking203** [comment]
ready for Review
