### ISSUE TITLE
Aktivitäten anzeigen (UC 2)

### ISSUE THREAD

**Issue by simbra92** [sweIhm/sweiproject-tg1a-2#2]
User Story:
Als Programmkoordinatorin will ich mir anzeigen lassen, in welchem Gebiet die meisten Forschungsaktivitäten stattfinden.

Akzeptanzkriterien:
- Übersicht aller Aktivitäten
- Aktivitäten sind nach eindeutiger Erstell-ID absteigend sortiert

**Comment by maxiking203** [comment]
Im Fachklassenmodel ist die Verbindung zwischen Post und PostDetails nicht klar. Evtl. brauchen wir hier ein Objekt vom Typ PostDetails oder Post. Vieleicht brauchen wir aber die Klasse PostDetails nicht mehr...

**Comment by simbra92** [comment]
PostDetails gibt es nicht mehr, als Liste im Post
