### ISSUE TITLE
Aktivitäten filtern (UC 3)

### ISSUE THREAD

**Issue by simbra92** [sweIhm/sweiproject-tg1a-2#3]
User Story: 
Als Professor/in will ich wissen, welche Aktivitäten es in meinem Bereich gibt.

Akzeptanzkriterien:
- Übersicht der Aktivitäten meines Fachbereichs
- Aktivitäten sind nach Aktualität geordnet

**Comment by brumma-man** [comment]
Akzeptanz erfüllt, aber noch keine fuzzy search.
